### ISSUE TITLE
IListConst.empty()

### ISSUE THREAD

**Issue by Solido** [marcglasberg/fast_immutable_collections#38]
Currently I use the form `const IListConst([])` but I would like to have a more expressive const IListConst.empty() to init my fields. Thoughts on this?

**Comment by marcglasberg** [comment]
It doesn't work, because of Dart limitations. Problem is you have to provide the typed const list it uses internally. So you have to provide the const `[]` inside of the `IListConst`. That's why you need to write const `IListConst([])` instead of simply const `IListConst()`.

When you provide the `[]` it's actually a const list of the type you want. For example: `List<String> myList = IListConst([])` means it's a const list of String, and not a list of dynamic.

Anyway, maybe I'm wrong here, so feel free to try it out yourself and see if you get it to work. I agree `IListConst([])` sucks.

**Comment by Solido** [comment]
I was expecting to something like this:

`const IListConst.empty([this.config = const ConfigList()]) : this._list = const [], super._gen();`

and then force the type on the left side with:

`IList<String> smth = const IListConst.empty()`

Seems to be accepted by the compiler just want to confirm with you @marcglasberg.

**Comment by marcglasberg** [comment]
Well, if it works, PR it.

Ideally we should have `const IList.empty()` and `const IList.constant([1, 2, 3])`. That would be ideal.

**Comment by LowLevelSubmarine** [comment]
I've just tried implementing `IList.constant()` and i was suprised that it seems to work:

### implementation (inside the IList class)
```dart
const factory IList.constant(List<T> list) = IListConst<T>;
```

### usage
```dart
var ilist2 = const IList.constant([1, 2, 3]);
ilist2 = ilist2.add(5);
ilist2.forEach((element) => print(element));
```

would you still be interested in this syntax? (people could still use IListConst)
maybe we should think about naming it const to be shorter and inline with the dart syntax though

**Comment by marcglasberg** [comment]
Yes!

Em dom., 7 de abr. de 2024 12:37, LowLevelSubmarine <
***@***.***> escreveu:
