### ISSUE TITLE
Add `firstWhereOrNull` method

### ISSUE THREAD

**Issue by torbenkeller** [marcglasberg/fast_immutable_collections#57]

**Comment by marcglasberg** [comment]
This method you want used to exist in FIC, but I've since removed it. This decision came about when the Dart authors introduced or expanded a native package, https://pub.dev/packages/collection and added some quite similar methods to those I had in FIC, some even bearing the same names.

To avoid duplication and potential conflicts, I decided to remove these overlapping methods from FIC, ensuring FIC's compatibility with the native `collection` package.

I recommend incorporating the `collection` package into your project as follows:

```
  collection: 1.17.0
```
