### ISSUE TITLE
const IList, ISet, IMap etc? 

### ISSUE THREAD

**Issue by chandu0101** [marcglasberg/fast_immutable_collections#9]
```dart
class Sample {
  final Ilist<String> list;
  Sample({ this.list = const <String>[].lock});
}
```
all default values of constructor should be const , how can i set default value for IList ?

above code fails with  `Context: Extension operations can't be used in constant expressions.`

**Comment by marcglasberg** [comment]
You should use this pattern instead:

```dart
class Sample {
  final IList<String> list;

  Sample({ Iterable list = const [] }) 
         : list = IList(list);
}
```

This way you can accept any `Iterable` in the constructor. Note, if the constructor is passed an `IList` it will just reuse the same instance (the `IList` constructor will return the original `list` instance if it's an `IList` already).

Also note: I intend on allowing for a const `IList` in the future, but that's not as easy as it seems, because the `IList` has mutable information. For example, it caches the `hashCode` and it can be "flushed". However, it is possible to allow for a const constructor, but it needs some work, and I haven't had the time yet.

**Comment by marcglasberg** [comment]
Version [5.0.0-dev.1 ] now has an experimental const IList.

Examples: 

`const IList<String> myList = IListConst.empty();`

`const IList<int> myList = IListConst([1, 2, 3]);`

**Comment by marcglasberg** [comment]
Version [5.0.0-dev.8] now has both a const IList and a const ISet.

It now also includes the necessary explanation in the Readme.

**Comment by sezaru** [comment]
Do you have any plans to add a const IMap too? I want to use your library with my redux AppState (which needs to be const), but without a const IMap, I cannot.

**Comment by marcglasberg** [comment]
@sezaru Sure, that's why this issue is still open. I just need to find the time.

However, why does your AppState need to be constant?

**Comment by venkatd** [comment]
@marcglasberg Perhaps we could sponsor the development of `IMapConst`?

**Comment by marcglasberg** [comment]
@venkatd Sure. I'll ping you in Whatsapp tomorrow and we can discuss it.

**Comment by marcglasberg** [comment]
Done: version 7.0.0.
